# Assignment 2.1: NumPy Array Basics
Python for Data Analytics | Module 2   
Professor James Ng

In [14]:
## SETUP: RUN, BUT DO NOT MODIFY 
import pandas as pd

## Section 1: Importing NumPy

In [15]:
# PROBLEM 1
# - Import the NumPy package according to the community convention

### BEGIN SOLUTION
import numpy as np
### END SOLUTION

## Section 2: Creating `ndarray` Objects

In [16]:
# Here is a heterogenous list containing int, float and str objects
section_2_list = [
    'If you can dream it', 234, 'you can do it.', -28.4, 
    'storm trooper', '823489', 8398, -1238, 18.3123, 83.12, 
    "Luke Skywalker's death was lame..."]

In [17]:
# PROBLEM 1
# - Convert this list to an `ndarray`
# - Assign it to a variable
# - Print it

### BEGIN SOLUTION
section_2_ndarray = np.array(section_2_list)
section_2_ndarray
    
### END SOLUTION

array(['If you can dream it', '234', 'you can do it.', '-28.4',
       'storm trooper', '823489', '8398', '-1238', '18.3123', '83.12',
       "Luke Skywalker's death was lame..."], dtype='<U34')

In [18]:
# PROBLEM 2
# So now you have an `ndarray` wherein everything has been
# converted to a string, which is a major problem for later analysis.

# Use your skills from module 1 to iterate over the `section_2_list` 
# object and separate the string, int, and float elements into
# separate lists and then create 3 `ndarray` objects from those lists

### BEGIN SOLUTION
ints = []
strings = []
floats = []

for element in section_2_list:
    if isinstance(element, str):
        strings.append(element)
    elif isinstance(element, int):
        ints.append(element)
    elif isinstance(element, float):
        floats.append(element)
        

string_array = np.array(strings)
int_array = np.array(ints)
float_array = np.array(floats)

string_array, int_array, float_array
    
### END SOLUTION

(array(['If you can dream it', 'you can do it.', 'storm trooper', '823489',
        "Luke Skywalker's death was lame..."], dtype='<U34'),
 array([  234,  8398, -1238]),
 array([-28.4   ,  18.3123,  83.12  ]))

In [19]:
# PROBLEM 3
# If you look carefully, you'll notice that there is one string
# in `section_2_list` that could be convert to an int.

# - Modify your answer to the previous problem so that when an element
#   of `section_2_list` is a string you attempt to convert it to an int.
# - If the conversion succeeds add it to your list of ints rather than the
#   list of strings. If it fails, add it to the list of strings

# And remember, catch the specific error class, it's good practice.

### BEGIN SOLUTION
ints = []
strings = []
floats = []

for element in section_2_list:
    if isinstance(element, str):
        try: 
            ints.append(int(element))
        except ValueError:
            strings.append(element)
    elif isinstance(element, int):
        ints.append(element)
    elif isinstance(element, float):
        floats.append(element)
        

string_array = np.array(strings)
int_array = np.array(ints)
float_array = np.array(floats)

string_array, int_array, float_array
    
### END SOLUTION

(array(['If you can dream it', 'you can do it.', 'storm trooper',
        "Luke Skywalker's death was lame..."], dtype='<U34'),
 array([   234, 823489,   8398,  -1238]),
 array([-28.4   ,  18.3123,  83.12  ]))

## Section 3: Numpy Array Attributes

In [20]:
# I'm going to load some data for you into a couple of `ndarray` objects.
# Don't worry about how I'm doing this right now.

!curl -L https://osf.io/95kys/download --create-dirs -o data-sets/nd-football-2017-roster.csv
nd_football_roster = pd.read_csv('data-sets/nd-football-2017-roster.csv')

# Here are the NumPy arrays for the next few problems
jersey_numbers = np.array(nd_football_roster['Number'])
player_height_and_weight = np.array(
    (nd_football_roster['Weight'], nd_football_roster['Height']))

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   459  100   459    0     0    743      0 --:--:-- --:--:-- --:--:--   742
100  4184  100  4184    0     0   3193      0  0:00:01  0:00:01 --:--:--  3193


This creates two NumPy arrays: 
1. `jersey_numbers` holds all the jersey numbers of our 2017 football players
1. `player_height_and_weight` holds official player height and weight data in a 2-dimensional array.

In [21]:
# PROBLEM 1
# - What are the number of dimensions for each of these arrays?
# - Print your answers using string formatting to specify which
#   answer belongs to which array

### BEGIN SOLUTION
print("jersey_numbers has {} dimensions".format(jersey_numbers.ndim))
print("player_height_and_weight has {} dimensions".format(player_height_and_weight.ndim))

### END SOLUTION

jersey_numbers has 1 dimensions
player_height_and_weight has 2 dimensions


In [22]:
# PROBLEM 2
# - What are the shapes for each of your arrays?
# - Print your answers with appropriate string interpolation

### BEGIN SOLUTION
print("jersey_numbers: ", jersey_numbers.shape)
print("player_height_and_weight: ", player_height_and_weight.shape)
### END SOLUTION

jersey_numbers:  (90,)
player_height_and_weight:  (2, 90)


In [23]:
# PROBLEM 3
# - What are the total number of elements in `player_height_and_weight`?

### BEGIN SOLUTION
player_height_and_weight.size
### END SOLUTION

180

In [24]:
# PROBLEM 4
# - What data type is held in each of your arrays?

### BEGIN SOLUTION
print(jersey_numbers.dtype, player_height_and_weight.dtype)
### END SOLUTION

int64 int64
