# Assignment 2.2: Selecting Data in NumPy Arrays
Python for Data Analytics | Module 2   
Professor James Ng

In [19]:
# SETUP: EXECUTE THIS CELL
import numpy as np
import pandas as pd

Throughout this assignment, you will use the following `ndarray` objects that come from our 2017 Notre Dame football roster again. I'll go ahead and load them for you.

In [20]:
!curl -L https://osf.io/95kys/download --create-dirs -o data-sets/nd-football-2017-roster.csv
nd_football_roster = pd.read_csv('data-sets/nd-football-2017-roster.csv')

player_jersey_numbers = np.array(nd_football_roster['Number'])
player_names_heights_and_weights = np.array(
    (nd_football_roster.Name, nd_football_roster['Height'], nd_football_roster['Weight']))

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   459  100   459    0     0   1095      0 --:--:-- --:--:-- --:--:--  1095
100  4184  100  4184    0     0   3936      0  0:00:01  0:00:01 --:--:-- 3213k


In [21]:
# Here is the data in those `ndarray` objects for your reference
player_jersey_numbers

array([ 2,  3,  4,  4,  5,  6,  7,  7,  9, 10, 12, 13, 14, 15, 17, 17, 18,
       19, 20, 21, 22, 23, 24, 24, 25, 26, 26, 27, 28, 29, 29, 32, 33, 34,
       35, 35, 37, 38, 38, 40, 40, 41, 41, 42, 42, 43, 44, 45, 46, 47, 48,
       49, 51, 53, 53, 54, 54, 55, 56, 57, 58, 62, 63, 64, 67, 68, 69, 70,
       71, 72, 74, 75, 77, 78, 80, 81, 82, 83, 85, 85, 86, 87, 88, 89, 91,
       93, 96, 97, 98, 99])

In [22]:
# This one is 2-Dimensional
player_names_heights_and_weights

array([['Dexter Williams', 'C.J. Sanders', "Te'von Coney",
        'Montgomery VanGorder', 'Nyles Morgan', 'Equanimeous St. Brown',
        'Nick Watkins', 'Brandon Wimbush', 'Daelin Hayes', 'Chris Finke',
        'Ian Book', 'Tyler Luatua', 'Devin Studstill', 'C.J. Holmes',
        'Nolan Henry', 'Isaiah Robertson', 'Troy Pride Jr.',
        'Justin Yoon', 'Shaun Crawford', 'Jalen Elliott', 'Asmar Bilal',
        'Drue Tranquill', 'Mick Assaf', 'Nick Coleman', 'Brandon Garcia',
        'Austin Webster', 'Ashton White', 'Julian Love',
        'Nicco Fertitta', 'Sam Kohler', 'Kevin Stepherson',
        'D.J. Morgan', 'Josh Adams', 'Tony Jones Jr.', 'Grant Hammann',
        'Donte Vaughn', 'Robert Regan', 'Deon McIntosh',
        'Christopher Schilling', 'Kier Murphy', 'Brett Segobiano',
        'Temitope Agoro', 'Jimmy Thompson', 'Julian Okwara',
        'Jeff Riney', 'Brian Ball', 'Jamir Jones', 'Jonathan Jones',
        'Matt Bushland', 'Chris Bury', 'Greer Martini', 'Brandon Hutson',

## Section 1: Using Index Notation

In [23]:
# PROBLEM 1
# - Create a list and append the 1st, 10th, and 78th elements
#   in player_jersey numbers to it and print your results
# - Remember that the 1st element of an array has an index of 0

### BEGIN SOLUTION

# Zero points for wrong index numbers. Index numbers asked for are STRICTLY 0, 9 and 77.

jerseys = []
jerseys.append(player_jersey_numbers[0])
jerseys.append(player_jersey_numbers[9])
jerseys.append(player_jersey_numbers[77])
jerseys
### END SOLUTION

[2, 10, 83]

In [25]:
# PROBLEM 2
# - Create an empty dict and use index notation to add player names as keys
#   and their heights as the values for the following players:
#   Sam Bush, Justin Yoon, Drue Tranquill

# Print your results

### BEGIN SOLUTION
player_data = {}

# Any approach is fine as long as student adds to a dict. The dict contents should look like the one below.
for index, item in enumerate(player_names_heights_and_weights[0]):
    if item in ["Sam Bush", "Justin Yoon", "Drue Tranquill"]:
        player_data[item] = player_names_heights_and_weights[1][index]    
player_data
### END SOLUTION

{'Justin Yoon': 70, 'Drue Tranquill': 74, 'Sam Bush': 76}

In [26]:
# PROBLEM 3
# - What are the jersey number, height, and weight of Mike McGlinchey?
# - You have to use index notation to derive this. No answering it directly. :)
# - Assign the results to well named variables or a dict.

# - HINT: The `enumerate` function can help you identify the index number
#   of Mike's records in the array objects.

### BEGIN SOLUTION
all_about_mike = {}

# here is the final structure to look for.
for index, item in enumerate(player_names_heights_and_weights[0]):
    if item == "Mike McGlinchey":
        all_about_mike["jersey"] = player_jersey_numbers[index]
        all_about_mike["height"] = player_names_heights_and_weights[1][index]    
        all_about_mike["weight"] = player_names_heights_and_weights[2][index]    
all_about_mike
### END SOLUTION

{'jersey': 68, 'height': 80, 'weight': 312}

In [8]:
# PROBLEM 4
# - What's the name of the next to last player in the roster? Any approach with correct answer gets full points.

### BEGIN SOLUTION
player_names_heights_and_weights[0][-2]
### END SOLUTION

'Andrew Trumbetti'

In [9]:
# PROBLEM 5
# - And what's his jersey number and height?
# - Print your results with string interpolation making it clear which is which.

### BEGIN SOLUTION
print("Andrew's Jersey #: {}".format(player_jersey_numbers[-2]))
print("Andrew's Height: {}".format(player_names_heights_and_weights[1][-2]))
### END SOLUTION

Andrew's Jersey #: 98
Andrew's Height: 76


In [10]:
# PROBLEM 6 - CHALLENGE PROBLEM!!
# - So you may have noticed that there are some players on the team who 
#   weigh more than 300 lbs!!

# - Iterate through the weight values in the `player_names_heights_and_weights` ndarray 
#   object and mutate (modify) them so that whenever you encounter a player over
#   300 lbs, you modify the entry to be 9999.

# - HINT: Make sure to check what `player_names_heights_and_weights` looks
#   like after your work.

# - IMPORTANT: This operation will modify your original data structures. If
#   you start to encounter unexplainable errors, you probably need to 
#   re-execute the cell that creates the array at the top of this notebook.

### BEGIN SOLUTION

# You may see a lot of this...
# But it won't work, assigning a new value to
# item just breaks the reference to the original element
# it doesn't modify the original element
#for item in player_names_heights_and_weights[2]:
#    if item > 300:
#        item = 999999
        

# Instead, the players need to obtain a reference to the 
# index of the item they wish to change, and use it 
# to update the value at that index. Enumerate is easiest,
# but you might see this too

index = 0
for item in player_names_heights_and_weights[2]:
    if item > 300:
        player_names_heights_and_weights[2][index] = 999999
    index += 1
    
player_names_heights_and_weights[2]
    
### END SOLUTION

array([202, 185, 235, 217, 238, 204, 203, 226, 255, 177, 205, 260, 198,
       206, 195, 208, 183, 195, 175, 208, 229, 230, 202, 187, 180, 191,
       197, 190, 179, 189, 180, 208, 220, 224, 183, 209, 203, 190, 217,
       225, 201, 190, 216, 235, 180, 193, 243, 227, 190, 242, 240, 237,
       231, 267, 999999, 999999, 235, 284, 999999, 999999, 280, 289,
       999999, 999999, 294, 999999, 999999, 999999, 999999, 292, 294,
       999999, 999999, 999999, 256, 225, 242, 224, 207, 181, 245, 227,
       220, 252, 251, 281, 999999, 299, 252, 999999], dtype=object)

## Section 2: Using Slice Notation to Create Array Views

In [11]:
# Let's reset the ndarray objects that you are working with
player_jersey_numbers = np.array(nd_football_roster['Number'])
player_names_heights_and_weights = np.array(
    (nd_football_roster.Name, nd_football_roster['Height'], nd_football_roster['Weight']))


In [12]:
# PROBLEM 1
# - Use Slice notation to get two views of `player_jersey_numbers`.
# - The first view should have the first 45 players, and the second 
#   should have the last 45.
# - Display your results

### BEGIN SOLUTION

# Students probably won't do this, just compare results
print(player_jersey_numbers[0: player_jersey_numbers.size // 2])
print(player_jersey_numbers[player_jersey_numbers.size // 2:])
### END SOLUTION

[ 2  3  4  4  5  6  7  7  9 10 12 13 14 15 17 17 18 19 20 21 22 23 24 24
 25 26 26 27 28 29 29 32 33 34 35 35 37 38 38 40 40 41 41 42 42]
[43 44 45 46 47 48 49 51 53 53 54 54 55 56 57 58 62 63 64 67 68 69 70 71
 72 74 75 77 78 80 81 82 83 85 85 86 87 88 89 91 93 96 97 98 99]


In [13]:
# PROBLEM 2
# - What are the elements with indexes 5-14 of each "row" of the 2-dimensional 
# - `player_names_heights_and_weights` ndarray? Display your results

# HINT: Remember, there is one row for names, one for heights, and 
# one for weights

### BEGIN SOLUTION
print(player_names_heights_and_weights[0][5:15])
print(player_names_heights_and_weights[1][5:15])
print(player_names_heights_and_weights[2][5:15])
### END SOLUTION

['Equanimeous St. Brown' 'Nick Watkins' 'Brandon Wimbush' 'Daelin Hayes'
 'Chris Finke' 'Ian Book' 'Tyler Luatua' 'Devin Studstill' 'C.J. Holmes'
 'Nolan Henry']
[77 73 73 75 69 72 75 72 72 72]
[204 203 226 255 177 205 260 198 206 195]
